name: life_plane_go
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.0.0
  shared_preferences: ^2.2.2
  video_player: ^2.7.0
  cupertino_icons: ^1.0.8
  vibration: ^2.0.0
  dropdown_button2: ^2.3.9
  image_picker: ^1.0.7
  glass_kit: ^2.0.0
  http: ^0.13.0 # ðŸ‘‰ Ð´Ð¾Ð±Ð°Ð²Ð»ÐµÐ½Ð¾ Ð´Ð»Ñ Ð·Ð°Ð¿Ñ€Ð¾ÑÐ¾Ð² Ðº Ð±ÑÐºÐµÐ½Ð´Ñƒ
  flutter_localizations: # ðŸ‘‰ Ð´Ð»Ñ Ð¿Ð¾Ð´Ð´ÐµÑ€Ð¶ÐºÐ¸ Ð»Ð¾ÐºÐ°Ð»Ð¸Ð·Ð°Ñ†Ð¸Ð¹
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true # ðŸ‘‰ Ð²ÐºÐ»ÑŽÑ‡Ð¸Ñ‚ÑŒ Ð³ÐµÐ½ÐµÑ€Ð°Ñ†Ð¸ÑŽ ÐºÐ¾Ð´Ð° Ð¸Ð· .arb Ñ„Ð°Ð¹Ð»Ð¾Ð²

  assets:
    - assets/images/
    - assets/icons/
    - assets/videos/
